# Generated by Django 3.0 on 2020-10-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200915_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tecnologia'), ('MINE', 'Minecraft'), ('GR', 'Geral')], default='GR', max_length=4),
        ),
    ]
