# Generated by Django 3.0 on 2020-10-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aproved',
            field=models.BooleanField(default=True),
        ),
    ]
